// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	autentikasi "Gurumu/features/autentikasi"

	mock "github.com/stretchr/testify/mock"
)

// AutentikasiData is an autogenerated mock type for the AutentikasiData type
type AutentikasiData struct {
	mock.Mock
}

// Login provides a mock function with given fields: email
func (_m *AutentikasiData) Login(email string) (autentikasi.Core, error) {
	ret := _m.Called(email)

	var r0 autentikasi.Core
	if rf, ok := ret.Get(0).(func(string) autentikasi.Core); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(autentikasi.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAutentikasiData interface {
	mock.TestingT
	Cleanup(func())
}

// NewAutentikasiData creates a new instance of AutentikasiData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAutentikasiData(t mockConstructorTestingTNewAutentikasiData) *AutentikasiData {
	mock := &AutentikasiData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
