// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// JadwalHandler is an autogenerated mock type for the JadwalHandler type
type JadwalHandler struct {
	mock.Mock
}

// Add provides a mock function with given fields:
func (_m *JadwalHandler) Add() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// GetJadwal provides a mock function with given fields:
func (_m *JadwalHandler) GetJadwal() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

type mockConstructorTestingTNewJadwalHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewJadwalHandler creates a new instance of JadwalHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJadwalHandler(t mockConstructorTestingTNewJadwalHandler) *JadwalHandler {
	mock := &JadwalHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
